# Generated by Django 5.0.6 on 2024-11-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
