# Generated by Django 5.0.6 on 2024-11-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_address_order_customer_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
